name: Generate Profile Stats

on:
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Generate GitHub Stats
      - name: Generate Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: satyaki2001
          token: ${{ secrets.GITHUB_TOKEN }}
          output: assets/stats.svg

      # Generate Top Languages
      - name: Generate Top Languages
        uses: anuraghazra/github-readme-stats@master
        with:
          username: satyaki2001
          token: ${{ secrets.GITHUB_TOKEN }}
          layout: compact
          output: assets/top-langs.svg

      # Generate Trophies
      - name: Generate Trophies
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: satyaki2001
          output: assets/trophies.svg

      # Commit files
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/*.svg
          git commit -m "Update profile stats" || echo "No changes"
          git push
